// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFHfArf77UQv86g004r5bRDWBs1jdq4gg',
    appId: '1:654611573648:web:074ca2f26f592ef0982115',
    messagingSenderId: '654611573648',
    projectId: 'neuramap-8b66c',
    authDomain: 'neuramap-8b66c.firebaseapp.com',
    storageBucket: 'neuramap-8b66c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG8L_EHYvBuv6KO9v4vTDAI9tU4T-20aY',
    appId: '1:654611573648:android:1c1b13bdc9f982c0982115',
    messagingSenderId: '654611573648',
    projectId: 'neuramap-8b66c',
    storageBucket: 'neuramap-8b66c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD41X4IkKd234GAelxaTZbJeJ58Rd9EtyU',
    appId: '1:654611573648:ios:a1ec9d5c15baa1f4982115',
    messagingSenderId: '654611573648',
    projectId: 'neuramap-8b66c',
    storageBucket: 'neuramap-8b66c.appspot.com',
    iosClientId: '654611573648-ks4i8qqqnc5dujfer6p1lhb650pffp3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD41X4IkKd234GAelxaTZbJeJ58Rd9EtyU',
    appId: '1:654611573648:ios:a1ec9d5c15baa1f4982115',
    messagingSenderId: '654611573648',
    projectId: 'neuramap-8b66c',
    storageBucket: 'neuramap-8b66c.appspot.com',
    iosClientId: '654611573648-ks4i8qqqnc5dujfer6p1lhb650pffp3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );
}
